image: "julia:1"

cache:
  paths:
    - .julia

stages:
  - build
  - test
  - testdocs
  - deploy

build:
  stage: build
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build("ConScape");
                          using ConScape;'

test:
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("ConScape"; coverage=true);'
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit_local(process_folder())'
  variables:
    CODECOV_TOKEN: "0c79cb5b-3787-4892-9d2b-7131a41c35d4"

weave:
  stage: test
  script:
    # Temporarily add Weave like this until we have a released version of ConScape to use for Weave files
    - julia --project -e 'using Pkg;
                          Pkg.add(PackageSpec(name="Weave"));'
    - julia --project --color=yes examples/make.jl

test:docs:
  stage: testdocs
  dependencies:
    - test
  script:
    # workaround for https://github.com/JuliaDocs/Documenter.jl/issues/686
    - apt-get -qq update; apt-get -y install git
    - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
    - julia --project=docs --color=yes docs/make.jl
  artifacts:
    paths:
      - docs/build
  only:

pages:
  stage: deploy
  dependencies:
    - test:docs
  script:
    - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - master
