project:
    type: book
    output-dir: "../build"

book:
    page-navigation: true
    title: "ConScape.jl"
    # site-url: "https://conscape.github.io/site" 
    repo-url: https://github.com/ConScape/ConScape.jl
    author: 
        name: "Bram van Moorter and Rafael Schouten"
        email: "rafaelschouten@gmail.com"
    date: "2025-05-08"
    chapters:
        # logo: "images/stickerConScape.png"
        # pinned: true
        - part: index.qmd
          chapters:
            - quick_start.qmd
            - faq.qmd 
            - glossary.qmd
            - background.qmd
        - part: applications/index.qmd
          chapters:
            - applications/GI.qmd
            - applications/EIA.qmd
        - part: "Tutorials"
          chapters:
            # - notebooks/index.qmd
            - notebooks/nbk_getting_started.qmd
            - notebooks/nbk_landmarks.qmd
            - notebooks/nbk_windowing.qmd
            - notebooks/nbk_distance_metrics.qmd
            - notebooks/nbk_cost.qmd
            - notebooks/nbk_functionality_variants.qmd
        - api.qmd 
    navbar: 
        background: primary
        right: 
        - text: Version
          menu: 
            - text: dev
        
    search: 
        location: sidebar
        type: textbox

    twitter-card: true
    open-graph: true
    repo-actions: [issue]

toc-title: "Table of Contents"

execute:
    echo: false
    output: true
    cache: false
    freeze: false

bibliography: references.bib

format:
    html:
        include-in-header: 
            file: _static/versions.html
        code-link: true
        number-sections: false
        resources: 
            # - _static/style.css
            - _static/versions.html
            # - _static/theme.scss
        theme: 
            light: 
                # - _static/theme.scss
                - flatly
            dark: 
                # - _static/theme.scss
                - darkly
        code-overflow: wrap
        toc: true
        # css: _static/style.css
        css: styles.css
       
# format:
#   html:
#     theme: 
#       light: flatly
#       dark: darkly
#     code-copy: true
    
# project:
#   type: website

# website:
#   page-navigation: true
#   title: "ConScape - the docs"
#   site-url: "https://conscape.github.io/site" 
#   repo-url: https://conscape.github.io/site 

#   page-footer: 
#     right: "This page is powered by [Quarto](https://quarto.org/)."

#   sidebar: 
#     logo: "images/stickerConScape.png"
#     pinned: true
#     align: center
#     style: "docked"
#     search: true
#     collapse-level: 1
#     contents:
#       - section: "Home"
#         contents:
#           - href: index.qmd
#             text: Welcome
#           - href: quick_start.qmd
#             text: Quick start
#       - href: background.qmd
#         text: Background
#       - section: applications/index.qmd
#         contents:
#           - href: applications/GI.qmd
#             text: Green infrastructure
#           - href: applications/EIA.qmd
#             text: Environmental impact assessment
#       - section: "Tutorials"
#         contents: 
#         - href: notebooks/index.qmd
#           text: Overview
#         - notebooks/nbk_getting_started.qmd
#         - notebooks/nbk_landmarks.qmd
#         - notebooks/nbk_distance_metrics.qmd
#         - notebooks/nbk_cost.qmd
#         - notebooks/nbk_functionality_variants.qmd
#       - faq.qmd
#       - glossary.qmd
#       - acknowledgments.qmd
#       - team.qmd
#       - blog.qmd
       
# format:
#   html:
#     theme: 
#       light: flatly
#       dark: darkly
#     code-copy: true
#     code-overflow: wrap
#     css: styles.css
#     toc: true

# execute: 
#   freeze: auto
