

```{julia}
rast.permeabilities
```

The information on affinity, cost and quality is stored in the `Grid` struct as
matrices. This is a 'dense' matrix (all elements are explicitly stored) in the
case of the source qualities:

```{julia}
typeof(g.source_qualities)
```

But, a sparse matrix (only the non-zero elements are explicitly stored) for the
affinities:

```{julia}
typeof(g.affinities)
```
costs:
```{julia}
typeof(g.costmatrix)
```

and target qualities:
```{julia}
typeof(g.target_qualities)
```

Note the target qualities can be provided either as a sparse (as demonstrated),
but also as a dense matrix. This sparse matrix representation forms the basis
for the landmark implementation to improve computational performance, as
demonstrated in Notebook.

The size of the landscape is given by:
```{julia}
(g.nrows * g.ncols, g.nrows * g.ncols)
```

# Step 2: `GridRSP` creation

After defining the ConScape `Grid` of the landscape between adjacent pixels _i_
and _j_, we need to compute the paths between non-adjacent source and target
pixels _s_ and _t_ using the randomized shortest paths framework. This step is
computationally intensive and to avoid recomputing central metrics within the
framework (e.g. the Z-matrix), we use the ConScape `GridRSP` struct to store
these metrics together with the `Grid`. In addition to being demanding in terms
of processing, this step is also demanding in terms of memory, because sparse
affinity and cost matrices are converted into dense matrices. We implemented
strategies to reduce memory footprint by using the sparse representation for the
target qualities as explained in Van Moorter et al. (2022) and Notebook on
[performance](/notebooks/nbk_landmarks.qmd). 

The `GridRSP` is computed from a `Grid` with the $\theta$ parameter to control
the amount of randomness in the paths ($\theta \rightarrow 0$ is random
movement, whereas $\theta \rightarrow \infty$ is optimal movement). 



Let's take, for illustrative purposes, pixel 88, 33 as our target:

```{julia}
#| eval: false
I = CartesianIndices(rast)[4300]
tmp = zeros(dims(rast))
tmp[I] = 1
Rasters.rplot(tmp; axis=(; title="One target pixel"))
```

The ecological distances from all _s_ to _t_ are:

```{julia}
ec_matrix = solve(ExpectedCost(), rsp, rast, 1, I)
ec_rast = Raster(ec_matrix[:, 4300], dims(rast))
plot(ec_rast; axis=(; title="Ecological distances to target pixel t"))
```

In many ecological applications we are not simply interested in the ecological
distances, but would rather know the proximity between _s_ and _t_ given a
movement capacity of the species (e.g. $\alpha = 75$):

```{julia}
ConScape.plot_values(g, map!(x -> exp(-x/75), dists[:,4300], dists[:,4300]), 
                        title = "Proximity to target pixel t")
```

A ConScape `Grid` describes a graph from a grid of adjacent cells or pixels. It
requires four main inputs: the quality of each pixel both as a source and as a
target, the affinity between _i_ and _j_ (i.e. probabilities of moving between
adjacent pixels _i_ and _j_), and the cost of moving between between _i_ and
_j_. However, these four inputs can be reduced, for instance, by considering the
quality of a pixel identical as a source and target, or by defining the cost as
a function of the affinities (e.g. a logarithmic relationship). For our
illustration, we introduced those two simplifications and only provided two
independent data: the quality of a pixel (identical as source and as target) and
the likelihood of moving between adjacent pixels. The likelihood of moving
between adjacent pixels _i_ and _j_ was derived from a 'permeability map', which
describes the permeability of a pixel _i_ (and is similar to the conductivity in
circuit theory). The function graph matrix from raster computes the values for
an _i_ − _j_ pair from the map either by the average permeability of _i_ and _j_
(`AverageWeight`) or by the permeability of the target pixel _j_
(`TargetWeight`; the default); the neighbors of a pixel can be defined either as
rook (`N4`) or as queen (`N8`; the default).

From the `Grid`, we can plot the qualities of the pixels: