---
title: "Ecological distance"
bibliography: biblio.bib
engine: julia
---

::: {.callout-tip}
## Here you will learn

Different ecological distance and proximity metrics implemented in ConScape.
:::

# Demonstration of distance and proximity metrics

In this notebook we demonstrate different types of distances and proximities
that can be used in ConScape to quantify the connectivity between source and
target pixels.


## Data import, `Grid` and `GridRSP` creation

See notebook [Getting Started](/notebooks/nbk_getting_started.qmd) for a 'basic
workflow' to learn about the fundamentals on data import and the creation of a
ConScape `Grid`:

```{julia}
#using Pkg
#Pkg.activate(joinpath(ENV["HOME"], ".julia", "dev", "ConScape"))

using ConScape
using Rasters
using ArchGDAL
using Statistics
using Plots
```

```{julia}
#| echo: false
#| eval: true

datadir = joinpath(dirname(pathof(ConScape)), "..", "data")
```

```{julia}
mov_prob = Raster(joinpath(datadir, "mov_prob_1000.asc"); missingval=NaN)
hab_qual = Raster(joinpath(datadir, "hab_qual_1000.asc"); missingval=NaN)
```

```{julia}
non_matches = xor.(isnan.(mov_prob), isnan.(hab_qual))
mov_prob[non_matches] .= 1e-20
hab_qual[non_matches] .= 1e-20;
```

```{julia}
theta = 0.001
rast = RasterStack((; permeabilities=mov_prob, qualities=hab_qual))
rsp = RSP(; theta, distance_transformation=MinusLog())
```

## Euclidean distance

Compute the Euclidean distance between all pairs of source and target pixels:
```{julia}
euclid = solve(Distance(), Euclidean(), rast)
```

The distance from all source pixels to a given target pixel (e.g. pixel 4300):

```{julia}
#| fig-cap: Euclidean distance to target t.
#| fig-subcap: 
#|   - "a"
#|   - "b"
#| layout-ncol: 2

location_demo = mask(zeros(dims(rast); missingval=NaN); with=rast)
location_demo[4300] = 1
plot(location_demo; axis=(; title="Target")) |> display
plot(Raster(euclid[:, 4300], dims(rast)); 
    axis=(; title="Euclidean distance"),
) |> display
```


## Least-cost distance

From the `Grid` we can also compute the least-cost distances betweem $s$ and $t$:
```{julia}
lcps = solve(Distance(), LeastCost(), rast)
```

The least-cost distance from all source pixels to target pixel 4300 is:
```{julia}
#| fig-cap: Least-cost distance to target t.

plot(Raster(lcps[4300, :], dims(rast)), axis=(; title="Least-cost distance"))
```

Not too surprising there is a high, albeit imperfect, correlation between the
Euclidean and least-cost distance:

```{julia}
cor(euclid[:, 4300], lcps[4300, :])
```

## RSP expected cost distance

The randomized shortest path (RSP) expected cost distance is the expected cost
of moving from the source to the target following the RSP distribution:  

```{julia}
dists = solve(ExpectedCost(), rsp, rast)
```

The RSP expected cost from all pixels as sources to target pixel 4300:
```{julia}
#| fig-cap: RSP expected cost distance to target t.

dist_rast = Raster(dists[:, 4300], dims(rast))
plot(dist_rast; axis=(; title="RSP expected cost distance"))
```

Comparing the least-cost distance to the RSP expected cost distance we see there
is strong positive relationship:

```{julia}
cor(lcps[:, 4300], dists[:, 4300])
```

Most computations in ConScape require a proximity instead of a distance. A
proximity is a metric from zero to one, with zero no connectivity and one
perfect connectivity between a source and a target. Different transformations
can be used for this, a common choice is the exponential transformation with a
scaling factor (here: 1000) representing the movement capabilities of a species
(see [@vanmoorter2021defining] for a discussion):

```{julia}
#| fig-cap: RSP expected cost proximity (logarithm) to target t.

dist_rast = Raster(map(x -> exp(-x / 1000), dists[:, 4300]), dims(rast))
plot(dist_rast; axis=(; title="Proximity"))
```

## Survival probability

[@fletcher2019towards] introduced the use of the 'absorbing Markov chain' or
'killed random walk' to connectivity modeling in landscape ecology (see also:
[@vanmoorter2021defining]). The RSP framework uses the same formalism and can be
considered a generalization of the absorbing Markov chain in
([@fletcher2019towards]) with the introduction of the $\theta$ paramter, see
([@vanmoorter2021defining]) for discussion. Here we show ConScape's
functionality to use the survival probability from source to target as a
proximtiy metric:  

```{julia}
#| fig-cap: Survival proximity to target t.

surv_prob = solve(SurvivalProbability(), rsp, rast)
sp_rast = Raster(surv_prob[:, 4300], dims(rast))
plot(sp_rast; axis=(; title="Survival proximity"))
```

The proximity based on the expected cost and on the survival probability show a
strong positive relationship:

```{julia}
cor(map(x -> exp(-x/1000), dists[:, 4300]), surv_prob[:, 4300])
```

For more discussion on the use of the survival probability, in the context of
the RSP framework we refer to ([@vanmoorter2021defining]) and more specifically
in the context of ConScape to Notebook [dispersal
mortality](/notebooks/nbk_cost.qmd).

## Summary

In ConScape different metrics are available to characterize the connectivity
between source and target pixels. The metric that is most appropriate will
depend upon the ecological application. [@vanmoorter2021defining] suggest the
use of the RSP expected cost for applications modeling individuals that move
with knowledge of their landscape, whereas the survival probability is probably
a more appropriate model for dispersing individuals experiencing mortality
([@fletcher2019towards] for this last type of applications). 