---
title: "Dispersal mortality"
bibliography: biblio.bib
engine: julia
---

::: {.callout-tip}
## Here you will learn

In this notebook, we demonstrate the possibility to use independent movement
probablities and costs, similar to [@fletcher2019towards] and [@marx2020samc].

:::

# Demonstration of independent likelihood and cost of movement

In this notebook, we demonstrate the possibility to use independent movement
probablities and costs, similar to [@fletcher2019towards] and [@marx2020samc].  

## Preamble

See notebook [Getting Started](/notebooks/nbk_getting_started.qmd) for a 'basic
workflow' to learn about the fundamentals on data import and the creation of a
ConScape `Grid`:

```{julia}
#using Pkg
#Pkg.activate(joinpath(ENV["HOME"], ".julia", "dev", "ConScape"))

using ConScape
using Rasters
using ArchGDAL
using Statistics
using Plots
```

```{julia}
#| echo: false
#| eval: true

datadir = joinpath(dirname(pathof(ConScape)), "..", "data")
```

We use the data provided in [@marx2020samc]:

```{julia}
mov_prob = Raster(joinpath(datadir, "prob_panther_cropped.asc"); missingval=NaN)
hab_qual = Raster(joinpath(datadir, "prob_panther_cropped.asc"); missingval=NaN)
```

Note, we did not have quality data for each pixel, for this demonstration we
simply assumed that the permeability adequately represents quality (see Notebook
[Getting Started](/notebooks/nbk_getting_started.qmd) for a better example with
independent quality data).

We remove negative values:
```{julia}
mov_prob = max.(0, mov_prob)
hab_qual = max.(0, hab_qual);
```

## Cost data

In addition to the data on the habitat quality and the likelihood of movement,
we also have independent data on the cost of movement ([@marx2020samc]):

```{julia}
mov_cost = Raster(joinpath(datadir, "mort_panther_cropped.asc"); missingval=NaN)
mov_cost = max.(0, mov_cost);
```

As discussed in vanmoorter2021defining, to use the mortality risk as a cost in
the RSP framework, we need to define the cost as the negative logarithm of the
survival probability between adjacent pixels: 

```{julia}
mov_cost = -log.(1 .- mov_cost);
```

We create the `Grid` by using these cost data, instead of a transformation from
the likelihood of movement:

```{julia}
rast = RasterStack((; permeabilities=mov_prob, costs=mov_cost, qualities=hab_qual))
```

## Computing the survival probability

Now we can compute the `GridRSP`:

```{julia}
theta = 1.0
rsp = RSP(; theta, distance_transformation=MinusLog());
```

Note that to compute the survival probability from $s$ to $t$ corresponding to
the mortality cost associated to edges $(i,j)$, we need to set $\theta=1.0$
([@vanmoorter2021defining]).

The survival probability from all source pixels to a target pixel (e.g. 15000) is:

```{julia}
#| fig-cap: Survival probability to a target.
#| fig-subcap: 
#|   - "a"
#|   - "b"
#| layout-ncol: 2

tmp = zeros(dims(rast))
tmp[CartesianIndex(36, 87)] = 1
plot(tmp; axis=(; title="Target"))
```

```{julia}
targetinit = init(rsp, rast, 1, CartesianIndex(36, 87))
sp = solve(SurvivalProbability(), targetinit)
sp_rast = Raster(map(t -> t==1 ? NaN : t,  sp), dims(rast))
plot(sp_rast; axis=(; title="Survival probability"))
```

Finally, we can use these survival probabilities to compute for each pixel the
amount of habitat it is functionally connected to:

```{julia}
#| fig-cap: Amount of connected habitat based on survival connectivity.
rsp = RSP(; proximity_measure=SurvivalProbability(), theta, distance_transformation=MinusLog()) 
ch = solve(ConnectedHabitat(), rsp, rast)
plot(ch)
```

## Summary

The ConScape library allows users to define the cost of movement between
adjacent pixels both as a transformation from the likelihood of movement, but
also from independent cost data. This application is very useful to model
dispersal with mortality ([@fletcher2019towards]), but could also be applied in
combination with 'energy landscapes' discussed in: [@vanmoorter2021defining]. 